image: java:8-jdk
stages:
  - test
  - build
services:
  - 'mysql:5.5'
variables:
  MYSQL_DATABASE: moviedb
  MYSQL_CI_URL: jdbc:mysql://mysql/moviedb
  MYSQL_USER_NAME: root
  MYSQL_PASSWORD: root
  MYSQL_ROOT_PASSWORD: root
cache:
  paths:
    - .m2/repository
    - target
maven-test:
 image: maven:3.3.9-jdk-8
 stage: test
 script: "mvn test -B"
maven-build:
 stage: build
 image: maven:3.3.9-jdk-8
 script: "mvn package -U"
 artifacts:
    paths:
        - target/*.jar
