server:
  port: 8080
spring:
  datasource:
    url: ${MYSQL_CI_URL}
    username: ${MYSQL_USER_NAME}    
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true   
     
